### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by Straafe** [Sorashi/Cleverbot.Net#3]
Followed the how to and built the example, this is what happens after waiting a while after typing a message (same thing happens when you clone the example and build it from there as well) :

```
Type your message: Hi
Bot:
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cleverbot.Net.Io.Api.CleverbotUserAgent.<PostAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cleverbot.Net.Io.Api.CleverbotAskApi.<GetResponseAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cleverbot.Net.CleverbotSession.<SendAsync>d__15.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at cleverbotiotest.Program.Main() in D:\Dropbox\Dropbox\Projects\Personal\CleverBotTesting\cleverbotiotest\cleverbotiotest\Program.cs:line 21
```

**Comment by sorashi** [comment]
> The remote server returned an error: (504) Gateway Timeout.

Looks like a network timeout error. Could you please try running the program again to see if the error persists?

**Comment by Straafe** [comment]
Oh yea, it seems to be working now. What happened? Just something on the io servers? Is there anything I can do to avoid that from happening?

**Comment by sorashi** [comment]
I don't know about any traceable channel where the cleverbot.io providers would announce the server status.

Regarding what you can do about it on your side –
to avoid web exceptions use this:
```csharp
try {
  // code where an exception could be thrown
} catch (Exception e) {
  while(e is AggregateException)
    e = e.InnerException;
  if(e is WebException)
    Console.WriteLine("Network error: " + e.Message);
  else throw e;
}
```

**Comment by Straafe** [comment]
Thanks, Sorashi!
